### ISSUE TITLE
which framework?

### ISSUE THREAD

**Issue by anarcat** [FrameworkComputer/qmk_hid#37]
What hardware is this software for? I didn't realize Framework shipped any QMK stuff, is that for the new Framework 16 or does it also work on 13 and earlier?

Would be great to have that documented in the README.

**Comment by JohnAZoidberg** [comment]
Oh you're right, we don't mention it anywhere.
I'm sure you've found out by now, sorry for the late reply.
The Framework 16 keyboard uses QMK firmware: https://frame.work/tw/en/products/laptop16-diy-amd-7040?tab=modules

**Comment by anarcat** [comment]
It wasn't quite clear to me, and i guess still not absolutely clear: are you saying that *only* the FW16 does?

**Comment by JohnAZoidberg** [comment]
Yes, only Framework 16. It's a USB keyboard with its own RP2040 controller that runs QMK firmware.
The Framework 13's keyboard is connected to the embedded controller (EC).
Most of it is standard chrome EC code, you can find our customizations here: https://github.com/FrameworkComputer/EmbeddedController/blob/lotus-zephyr/zephyr/program/lotus/azalea/src/keyboard_customization.c
